from __future__ import annotations


DEMO_PRESETS = [
    {
        "label": "Support desk review risk",
        "query": "Compare Zendesk, Zoho Desk, and Freshdesk for support ticketing pain points.",
        "category": "Customer Support",
        "features": ["ticket_creation_and_assignment", "reporting_and_analytics"],
        "tools": ["Zendesk", "Zoho Desk", "Freshdesk"],
        "max_price": None,
        "top_k": 3,
    },
    {
        "label": "CRM under $30",
        "query": "Recommend a CRM for a small team that needs automation, workflow builder, reporting, and API integrations under $30.",
        "category": "Crm",
        "features": ["automation", "workflow_builder", "reporting_analytics", "api_integrations"],
        "tools": [],
        "max_price": 30.0,
        "top_k": 5,
    },
    {
        "label": "PM automation shortlist",
        "query": "Find affordable project management platforms with automation, reporting analytics, templates, and API integrations.",
        "category": "Project Management",
        "features": ["automation", "reporting_analytics", "templates", "api_integrations"],
        "tools": [],
        "max_price": 25.0,
        "top_k": 5,
    },
    {
        "label": "CRM vendor comparison",
        "query": "Compare Salesforce, HubSpot, and Pipedrive for a growing sales team that cares about automation, reporting, workflow builder, and pricing.",
        "category": "Crm",
        "features": ["automation", "workflow_builder", "reporting_analytics"],
        "tools": ["Salesforce", "HubSpot", "Pipedrive"],
        "max_price": None,
        "top_k": 3,
    },
    {
        "label": "Website builder launch stack",
        "query": "Find website builders for a startup launch that need API access, analytics, templates, SEO tools, and custom domains.",
        "category": "Website Builders",
        "features": ["api_access", "analytics", "templates", "seo_tools", "custom_domains"],
        "tools": [],
        "max_price": None,
        "top_k": 5,
    },
    {
        "label": "Password manager security",
        "query": "Recommend a password manager with SSO, secure sharing, 2FA/MFA, breach alerts, and strong team security.",
        "category": "Password Managers",
        "features": ["sso_integration", "secure_sharing", "2fa_mfa", "breach_alerts"],
        "tools": [],
        "max_price": None,
        "top_k": 5,
    },
    {
        "label": "Support procurement memo",
        "query": "Create a procurement-style recommendation memo for choosing a customer support platform for a 200-person company.",
        "category": "Customer Support",
        "features": ["ticket_creation_and_assignment", "priority_and_sla_management", "reporting_and_analytics", "customer_and_agent_portals"],
        "tools": [],
        "max_price": None,
        "top_k": 5,
    },
    {
        "label": "Open-source alternatives",
        "query": "Find open-source alternatives to Airtable or Notion for a team that wants self-hosted knowledge management.",
        "category": "All",
        "features": [],
        "tools": [],
        "max_price": None,
        "top_k": 5,
    },
]
